version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=task_management
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: